### ISSUE TITLE
Yolo V8 plotting issue

### ISSUE THREAD

**Issue by lakpriya76** [CelestialAmber/LunaGB#2]
I am very new to machine learning and Ultralytics. I tried to train YOLO V8 model for detecting typhoons worldwide using JPEG images and annotation files. When it runs, it doesnt do plotting. This kind of error message appears everytime I try. 
Traceback (most recent call last):
  File "D:\data\pythonProject\.venv\main.py", line 5, in <module>
    results = model.train(data="config.yaml", epochs=1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\data\.venv\Lib\site-packages\ultralytics\engine\model.py", line 673, in train
    self.trainer.train()
  File "D:\data\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 198, in train
    self._do_train(world_size)
  File "D:\data\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 418, in _do_train
    self.metrics, self.fitness = self.validate()
                                 ^^^^^^^^^^^^^^^
  File "D:\data\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 557, in validate
    metrics = self.validator(self)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\data\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\data\.venv\Lib\site-packages\ultralytics\engine\validator.py", line 199, in __call__
    self.print_results()
  File "D:\data\.venv\Lib\site-packages\ultralytics\models\yolo\detect\val.py", line 193, in print_results
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "C:\Users\wathsala\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    save_dir=self.save_dir, names=self.names.values(), normalize=normalize, on_plot=self.on_plot
     self.run()
  File "C:\Users\wathsala\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
                                 ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'values'
    self._target(*self._args, **self._kwargs)
  File "D:\data\.venv\Lib\site-packages\ultralytics\utils\plotting.py", line 854, in plot_images

Process finished with exit code 1
Can someone help me to solve this issue? Thank you very much in advance.

**Comment by CelestialAmber** [comment]
I think you have the wrong repository. Closing this issue
